/**
 * Content Ideation via LLM
 *
 * Uses OpenRouter to generate video content ideas for each agent,
 * based on their character profile.
 */

import {
  chatCompletion,
  isOpenRouterConfigured,
} from "../../integrations/openrouter/client";
import { logger } from "../../utils/logger";
import type { AgentCharacter } from "../configs/alice-character";

export interface VideoIdea {
  title: string;
  description: string;
  videoPrompt: string;
  thumbnailPrompt: string;
  duration: number;
  topic: string;
}

function buildIdeationSystemPrompt(character: AgentCharacter): string {
  return `${character.personality}

## Your Visual Style
${character.visualStyle}

## Your Content Topics
${character.topics.map((t) => `- ${t}`).join("\n")}

## Your Tone
${character.tone.join(", ")}

## Thumbnail Style
${character.thumbnailStyle}

## Content Safety - AVOID
${character.avoidTopics.map((t) => `- ${t}`).join("\n")}`;
}

function buildIdeationUserPrompt(
  character: AgentCharacter,
  recentTitles: string[]
): string {
  const avoidSection =
    recentTitles.length > 0
      ? `\n\n## Recent Videos (avoid repeating these topics)\n${recentTitles.map((t) => `- ${t}`).join("\n")}`
      : "";

  return `Generate a new video idea for your channel. The video will be generated by an AI video model (LTX-2), so the video prompt must describe a visual scene, NOT a talking-head or screencasted tutorial. Think cinematic, atmospheric, abstract.

## Example Titles for Inspiration
${character.exampleTitles.map((t) => `- "${t}"`).join("\n")}
${avoidSection}

Respond with ONLY a valid JSON object (no markdown, no explanation):

{
  "title": "Catchy video title (max 80 chars)",
  "description": "Brief description for viewers (1-2 sentences, max 200 chars)",
  "videoPrompt": "Detailed visual scene description for AI video generation. Describe camera movement, colors, objects, atmosphere, style. Be specific and cinematic. Max 500 chars.",
  "thumbnailPrompt": "Description of the thumbnail image to generate. Include style, colors, composition. Max 300 chars.",
  "duration": "6, 8, or 10 (seconds — pick one)",
  "topic": "one of your topic categories"
}`;
}

/**
 * Generate a video idea using LLM.
 *
 * @param character - Agent's content character profile
 * @param recentTitles - Recent video titles to avoid repetition
 */
export async function ideateVideo(
  character: AgentCharacter,
  recentTitles: string[] = []
): Promise<VideoIdea> {
  if (!isOpenRouterConfigured()) {
    throw new Error(
      "OpenRouter not configured - cannot ideate video content"
    );
  }

  const systemPrompt = buildIdeationSystemPrompt(character);
  const userPrompt = buildIdeationUserPrompt(character, recentTitles);

  const rawResponse = await chatCompletion(systemPrompt, userPrompt);

  // Parse JSON from response (handle markdown code blocks)
  const jsonStr =
    rawResponse.match(/```(?:json)?\s*\n?([\s\S]*?)\n?\s*```/)?.[1] ||
    rawResponse.match(/\{[\s\S]*\}/)?.[0] ||
    rawResponse;

  const parsed = JSON.parse(jsonStr.trim()) as VideoIdea;

  if (!parsed.title || !parsed.videoPrompt || !parsed.thumbnailPrompt) {
    throw new Error("LLM returned incomplete video idea");
  }

  // Enforce character limits (LLM may exceed the prompt instructions)
  parsed.title = parsed.title.slice(0, 80);
  parsed.description = (parsed.description || "").slice(0, 200);
  parsed.videoPrompt = parsed.videoPrompt.slice(0, 500);
  parsed.thumbnailPrompt = parsed.thumbnailPrompt.slice(0, 300);

  // Clamp duration to valid LTX-2 Pro values: 6, 8, or 10 seconds
  const validDurations = [6, 8, 10] as const;
  const raw = parsed.duration || 10;
  parsed.duration = validDurations.reduce((best, d) =>
    Math.abs(d - raw) < Math.abs(best - raw) ? d : best
  );

  logger.info(
    {
      agentId: character.agentId,
      title: parsed.title,
      duration: parsed.duration,
    },
    "Video idea generated"
  );

  return parsed;
}
